# Generated by Django 2.2 on 2019-04-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
            ],
        ),
    ]
